### ISSUE TITLE
Cant link my console to my PNID

### ISSUE THREAD

**Issue by RainbowStonerz** [PretendoNetwork/Pretendo#22]
Tryin to link my PNID that i made on web. Keep getting error code 022-2571 and the message says "The Nintendo Network ID you entered is already in use." dispite the fact im choosing link. Any way to fix this? I wanna use my beta server rights because I donated to the super mario teir. Cant find the error code in the search
Thank you in advance. :)

**Comment by RainbowStonerz** [comment]
Found out its because my NNID was the same as my PNID!

**Comment by geogolem** [comment]
> Found out its because my NNID was the same as my PNID!

I'm experiencing the same issue --> unfortunately none of the guides/documentation mentions that the PNID cannot be the same as the NNID...

**Comment by stijnieboy150** [comment]
> > Found out its because my NNID was the same as my PNID!
> 
> I'm experiencing the same issue --> unfortunately none of the guides/documentation mentions that the PNID cannot be the same as the NNID...

Well it think it does and in the discord is saying it so much

**Comment by jonbarrow** [comment]
> unfortunately none of the guides/documentation mentions that the PNID cannot be the same as the NNID...

Yes, it does.

### Wii U:

![Screenshot from 2024-05-08 10-46-15](https://github.com/PretendoNetwork/Pretendo/assets/27011796/d5dbb8c1-0952-48c0-9a53-73ad8e52c555)

### 3DS:

![Screenshot from 2024-05-08 10-47-12](https://github.com/PretendoNetwork/Pretendo/assets/27011796/580aa751-9b75-4669-89e6-c3d2b371eccf)

Regardless though, this should really be common sense? Why would the console allow you to link what it thinks is the same account multiple times. The console has no idea about what a "Pretendo Network ID" is, it just thinks everything is a NNID. So if a NNID is already linked to the console, and you try to link an account with the same username to it again, why would it let you do that?

**Comment by geogolem** [comment]
> > unfortunately none of the guides/documentation mentions that the PNID cannot be the same as the NNID...
> 
> Yes, it does.
> 
> ### Wii U:
> ![Screenshot from 2024-05-08 10-46-15](https://private-user-images.githubusercontent.com/27011796/328933299-d5dbb8c1-0952-48c0-9a53-73ad8e52c555.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxOTMyOTYsIm5iZiI6MTcxNTE5Mjk5NiwicGF0aCI6Ii8yNzAxMTc5Ni8zMjg5MzMyOTktZDVkYmI4YzEtMDk1Mi00OGMwLTlhNTMtNzNhZDhlNTJjNTU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDE4Mjk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4Yzk2ODc3ZDAyZDIzNjIzZDI3ZmRmYjFiMjk2N2MwZWRhZDc1MDQ3YmU0YmJkNTYwYzhjZWMzYmNhMmYyOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mlMJ-GLx8tAedW97MrI9fPX5kU4cFebnplPVPYeGCxw)
> 
> ### 3DS:
> ![Screenshot from 2024-05-08 10-47-12](https://private-user-images.githubusercontent.com/27011796/328933656-580aa751-9b75-4669-89e6-c3d2b371eccf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxOTMyOTYsIm5iZiI6MTcxNTE5Mjk5NiwicGF0aCI6Ii8yNzAxMTc5Ni8zMjg5MzM2NTYtNTgwYWE3NTEtOWI3NS00NjY5LTg5ZTYtYzNkMmIzNzFlY2NmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDE4Mjk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4MWU0N2EwOTdhMTkwMGI1N2JkYjdhMjNjMTMyMWFlZmIwZDQ2YWZhNTJhMTcyYTRjNTRjZTkwZWI5ZDgxN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OSxwESxzIUANm5O2lQTkloh6wHug5WTN6hF3q_qKt3s)
> 
> Regardless though, this should really be common sense? Why would the console allow you to link what it thinks is the same account multiple times. The console has no idea about what a "Pretendo Network ID" is, it just thinks everything is a NNID. So if a NNID is already linked to the console, and you try to link an account with the same username to it again, why would it let you do that?

I'm quite teksavvy and I ran into this issue too, so from my perspective (and maybe I'm wrong), it doesn't really seem common sense. To the contrary the opposite might seem to be "more common sense" -- the reason being is that PNID is sort of described as a replacement for NNID and there is also the ability to "swap" back and forth between the PNID and NNID etc. I think (unles they know better) people's initial reaction would be to create the PNID to be the same as the NNID.

I created my PNID on the PC using the same username as NNID and ran into this issue first on 3DS and also on WIIU. To resolve I created a new PNID with PNID as a suffix i.e. usernamePNID and all is well on both 3ds and wiiu. I also initially though the guides didn't properly warn not to user same userID for PNID as NNID; however, upon closer inspection did find mention of it in the guides as you pointed out.

I also did discover this homebrew on WIIU: https://github.com/Nightkingale/Wii-U-Account-Swap
Apparently this homebrew once setup could allow a user to have a NNID and PNID that are the same username and simply swap between them on the same user on the WIIU --> but this wont work for 3DS unless there is a similar homebrew.. anyway, for me I am using this homebrew on the WIIU just for convenience (no need to have a second user, but can simply swap between NNID and PNID on the same user).. but I am still using a different PNID username than my NNID one anyway.

**Comment by jonbarrow** [comment]
> the reason being is that PNID is sort of described as a replacement for NNID and there is also the ability to "swap" back and forth between the PNID and NNID etc.

You'd be wrong, then, and made incorrect assumptions about how this works without fully reading the documentation first. Nowhere in our documentation does it say you can swap between NNIDs and PNIDs. And nowhere do we say that these act as a replacement for the NNID system. To the console everything is a NNID, we have not replaced the NNID system. The only "swapping" that occurs from our patches is swapping the server URLs, making the console interact with our servers rather than Nintendo's. You do not "swap between PNIDs and NNIDs", you swap between server environments. But the local account system is entirely untouched.

If you're tech-savvy you probably should have realized that a device wouldn't let you link the same account to it multiple times. The Minecraft launcher does not allow you to link multiple of the same account to it, YouTube does not allow you to login to the same account twice, Discord does not allow you to login to the same account twice, etc.

This is how all devices/services which offer multi-user usage operate. Only one instance of an account can be linked at a time. The Wii U and 3DS are no different. So, yes, it really should be common sense that the console would not let you link multiple accounts with the same username to it at the same time.

> long before I attempted to set it up on 3ds/wiiU..

You should read the documentation fully before trying any sort of homebrew, for future reference.

> I also did discover this homebrew on WIIU: [Nightkingale/Wii-U-Account-Swap](https://github.com/Nightkingale/Wii-U-Account-Swap)

This homebrew modifies/backs up/restores your `account.dat` files to give the *illusion* of swapping between a NNID/PNID. The consoles normal behavior has not changed here. This homebrew just physically swaps your account files out for the account files of the other service.
