### ISSUE TITLE
error in splatoon

### ISSUE THREAD

**Issue by thanone2** [PretendoNetwork/Pretendo#47]
this is the first time starting splatoon on my wii u with my new account connected to pretendo, I had just completed the tutorial and was roaming the main lobby. I entered the public lobby entrance, when it asks me to accept news from splatoon, I accept, then it says an error has occurred and returns me to the main lobby. help please?

**Comment by dogmann112** [comment]
Copy pasted from the discord announcement they made about it.
This is caused by Nintendo's shutdown of the Spotpass (BOSS) servers.
When Nintendo closed Spotpass, they simply told your console to no longer retrieve Spotpass data, aside from a few system titles, and Pokemon Bank/Poke Transporter on 3DS. This is accomplished via PolicyList.
Nimble ( https://github.com/PretendoNetwork/Nimble/releases/tag/v3 ) is needed to redirect the PolicyList servers to Pretendo. Placing 30_nimble.rpx in /wiiu/environments/aroma/modules/setup will do so. You may additionally need to clear Splatoon's shared save data (NOT the save data for your Wii U user. Shared save data is not used for progression, deleting it will not impact your save file.) and/or unregister BOSS tasks via Inkay (L+Down+Select, Inkay->Boss Settings->Unregister BOSS Tasks).

**Comment by thanone2** [comment]
sorry forgot I put this post here, I was on that discord channel actually!
