### ISSUE TITLE
Do i need a real wii u to play on pretendo servers over CEMU? 

### ISSUE THREAD

**Issue by MarcosParengo** [PretendoNetwork/Pretendo#54]

**Comment by jonbarrow** [comment]
Yes

**Comment by MarcosParengo** [comment]
Will this change at some point? Or will we always have that requirement?

**Comment by jonbarrow** [comment]
This will always be a requirement. Our servers validate console data as part of our ban system. Without valid console dumps we are unable to securely issue console bans

**Comment by 995qa** [comment]
What about IP-bans and the removal of VPN support? It could help with bans

**Comment by jonbarrow** [comment]
IP bans are not only overly aggressive, but almost useless. And "remove VPN support" is not as simple as it sounds. For one, it's not even really possible to do effectively. It's a very manual process and things will slip. It also doesn't help with anyone who just rents their own server somewhere and runs their own VPN instance. And even if it could be done, it harms legitimate users who otherwise rely on those services. Not even large companies like Discord try to tackle VPNs like that

IP bans, as mentioned, can always be worked around with a VPN. Which, as mentioned, cannot simply be "turned off". Also it only even works with people who have static IPs. As soon as an IP rolls, it's no longer banned (which is more common than you'd think)
